language: node_js
node_js:
  - 9.11.1

git:
  depth: 3

cache:
  pip: true
  directories:
  - node_modules

install:
- pip install grow --user
- npm install -g gulp-cli
- npm install -g firebase-tools
- npm install

jobs:
  include:
    - stage: build
      script:
      - echo 'Building locales None, en, de, and es...' && echo -en 'travis_fold:start:build\\r'
      - travis_wait grow build --re-route --locale None --locale en --locale de --locale es
      - echo -en 'travis_fold:end:build\\r'
      - echo 'Installing gsutil...' && echo -en 'travis_fold:start:install_gsutil\\r'
      - pip install gsutil --user # can't do this before grow has run, as the oath2client is incompatible
      - echo -en 'travis_fold:end:install_gsutil\\r'
      - echo 'Uploading build directory...' && echo -en 'travis_fold:start:upload_build\\r'
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then gsutil -m cp -r build/* gs://ampproject-b5f4c.appspot.com; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then gsutil -m cp -r build/* gs://ampproject-staging.appspot.com; fi'
      - echo -en 'travis_fold:end:upload_build\\r'
    - stage: build
      script:
      - echo 'Building locales fr, id, and ja...' && echo -en 'travis_fold:start:build\\r'
      - travis_wait grow build --re-route --locale fr --locale id --locale ja
      - echo -en 'travis_fold:end:build\\r'
      - echo 'Installing gsutil...' && echo -en 'travis_fold:start:install_gsutil\\r'
      - pip install gsutil --user # can't do this before grow has run, as the oath2client is incompatible
      - echo -en 'travis_fold:end:install_gsutil\\r'
      - echo 'Uploading build directory...' && echo -en 'travis_fold:start:upload_build\\r'
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then gsutil -m cp -r build/* gs://ampproject-b5f4c.appspot.com; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then gsutil -m cp -r build/* gs://ampproject-staging.appspot.com; fi'
      - echo -en 'travis_fold:end:upload_build\\r'
    - stage: build
      script:
      - echo 'Building locales it, ko, and pt_BR...' && echo -en 'travis_fold:start:build\\r'
      - travis_wait grow build --re-route  --locale it --locale ko --locale pt_BR
      - echo -en 'travis_fold:end:build\\r'
      - echo 'Installing gsutil...' && echo -en 'travis_fold:start:install_gsutil\\r'
      - pip install gsutil --user # can't do this before grow has run, as the oath2client is incompatible
      - echo -en 'travis_fold:end:install_gsutil\\r'
      - echo 'Uploading build directory...' && echo -en 'travis_fold:start:upload_build\\r'
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then gsutil -m cp -r build/* gs://ampproject-b5f4c.appspot.com; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then gsutil -m cp -r build/* gs://ampproject-staging.appspot.com; fi'
      - echo -en 'travis_fold:end:upload_build\\r'
    - stage: build
      script:
      - echo 'Building locales tr, zh_CN, and ru...' && echo -en 'travis_fold:start:build\\r'
      - travis_wait grow build --re-route  --locale tr --locale zh_CN --locale ru
      - echo -en 'travis_fold:end:build\\r'
      - echo 'Installing gsutil...' && echo -en 'travis_fold:start:install_gsutil\\r'
      - pip install gsutil --user # can't do this before grow has run, as the oath2client is incompatible
      - echo -en 'travis_fold:end:install_gsutil\\r'
      - echo 'Uploading build directory...' && echo -en 'travis_fold:start:upload_build\\r'
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then gsutil -m cp -r build/* gs://ampproject-b5f4c.appspot.com; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then gsutil -m cp -r build/* gs://ampproject-staging.appspot.com; fi'
      - echo -en 'travis_fold:end:upload_build\\r'
    - stage: deploy
      install:
      - npm install -g firebase-tools
      script:
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then firebase use production; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then firebase use staging; fi'
      - mkdir build

      - echo 'Installing urllib3 and gsutil...' && echo -en 'travis_fold:start:install\\r'
      - pip install urllib3[secure]
      - pip install gsutil --user
      - echo -en 'travis_fold:end:install\\r'

      - echo 'Listing build output from parallel jobs...' && echo -en 'travis_fold:start:list_remote_build\\r'
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then gsutil ls gs://ampproject-b5f4c.appspot.com/; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then gsutil ls gs://ampproject-staging.appspot.com/; fi'
      - echo -en 'travis_fold:end:list_remote_build\\r'

      - echo 'Downloading build output from parallel jobs...' && echo -en 'travis_fold:start:download_build\\r'
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then gsutil -m rsync -r gs://ampproject-b5f4c.appspot.com/ build; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then gsutil -m rsync -r gs://ampproject-staging.appspot.com/ build; fi'
      - echo -en 'travis_fold:end:download_build\\r'

      - echo 'Listing contents of build/...' && echo -en 'travis_fold:start:list_local_build\\r'
      - ls build
      - echo -en 'travis_fold:end:list_local_build\\r'

      - echo 'Deploying to firebase...' && echo -en 'travis_fold:start:deploy_firebase\\r'
      # TODO: renenable: - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
      - echo -en 'travis_fold:end:deploy_firebase\\r'

branches:
  only:
  - production
  - master
  - parallel

env:
  global:
    secure: RRx3CaLmCC0rA+MOYXTI3HTAMc2TI9AQcodUfZhr+vNEL8d0q09EZkYU/TjkRx9VQ1paOT1AmxNQJtHhysIS7B/pSAZoNG9bPC5UXmiZHVLbRB4qPmMMte9zdfKanGY3/g3zt2qOTUVVL4ymDy5xK2uYZ/KgkrDx1gGH3mSoTO6gK79I4nisJYDcRfzI/UUvrNkdjlFYrFnZbnMdnqZSryuv7CrdZWpYtLDryzJ+bcgq6Vr2liiKwmVb+/tff3EblAzBcWMAM4I0MzRaM+Mahw0EEENc24brtVoQTbvSdXXJ9CEIfWjykSyZh0WrZkx3tKY95GDr9PCHEkyI5d2kUGYDbRjjrEuBEdPTcjx6zZ2vXUlVPeDxNwLO1WZwVy0Om1dg/jwPjVDtsubjBaC+4XezJCywaZruGD6Q0iStemMVapN19SbGJzo9uYG8EvVB4OFlmY2l/fOadTIC9YHpYJREhGc2DBW9jHfTK1dgyW1JpnFgieEOSw24gsvbxSSV5db7tJU36Pt1Kkcu3IZnYyHlBUmYKZ24cizh6azfkHRaLvSvdJuvx0euuoz/WOJ77toUD6wPc0/OtrKnkCfQowtciMdnKNhuu4JpegdZ9gQqpV2gQ0XpPgxc4afKCd0L5QiUNFCu1J+fQ0obclqWZpC0VzHdDpNMckv4I7XqnhI=
